# Generated by Django 2.0 on 2023-04-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
