# Generated by Django 4.1.7 on 2023-06-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.CharField(max_length=100)),
                ('BusinessTravel', models.CharField(max_length=100)),
                ('DailyRate', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('DistanceFromHome', models.CharField(max_length=100)),
                ('Education', models.CharField(max_length=100)),
                ('EducationField', models.CharField(max_length=100)),
                ('EnvironmentSatisfaction', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('HourlyRate', models.CharField(max_length=100)),
                ('JobInvolvement', models.CharField(max_length=100)),
                ('JobLevel', models.CharField(max_length=100)),
                ('JobSatisfaction', models.CharField(max_length=100)),
                ('MaritalStatus', models.CharField(max_length=100)),
                ('MonthlyIncome', models.CharField(max_length=100)),
                ('MonthlyRate', models.CharField(max_length=100)),
                ('NumCompaniesWorked', models.CharField(max_length=100)),
                ('OverTime', models.CharField(max_length=100)),
                ('PercentSalaryHike', models.CharField(max_length=100)),
                ('PerformanceRating', models.CharField(max_length=100)),
                ('RelationshipSatisfaction', models.CharField(max_length=100)),
                ('StandardHours', models.CharField(max_length=100)),
                ('StockOptionLevel', models.CharField(max_length=100)),
                ('TotalWorkingYears', models.CharField(max_length=100)),
                ('TrainingTimesLastYear', models.CharField(max_length=100)),
                ('WorkLifeBalance', models.CharField(max_length=100)),
                ('YearsAtCompany', models.CharField(max_length=100)),
                ('YearsInCurrentRole', models.CharField(max_length=100)),
                ('YearsSinceLastPromotion', models.CharField(max_length=100)),
                ('YearsWithCurrManager', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
